sudo: false
language:
  - python
python:
  - "3.8"
before_install:
  - pip install -r requirements.txt
script:
  - python3 -m pytest --pylint --pylint-rcfile=./pylint.rc --pylint-error-types=EF --pylint-jobs=4
  - python3 tests.py --verbose
notifications:
  email: false
